# Generated by Django 3.0.7 on 2020-07-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=50)),
                ('prod_name', models.CharField(default='', max_length=50)),
                ('prod_desc', models.CharField(default='', max_length=1000)),
                ('prod_price', models.IntegerField()),
                ('prod_category', models.CharField(default='', max_length=100)),
                ('prod_image', models.ImageField(default='', upload_to='static/images')),
            ],
        ),
    ]
