# Generated by Django 3.0.7 on 2020-07-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='bestseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestseller_name', models.CharField(default='', max_length=50)),
                ('bestseller_image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
