# Generated by Django 3.0.7 on 2020-07-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_bestseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=50)),
                ('brand_image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
