# Generated by Django 3.0.7 on 2020-07-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0008_checkoutorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='address2',
            field=models.CharField(default='', max_length=500),
        ),
    ]
