# Generated by Django 3.0.7 on 2020-07-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0009_checkoutorder_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='products',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='total',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='zip_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
