# Generated by Django 3.0.7 on 2020-07-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0010_auto_20200713_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
