# Generated by Django 3.0.7 on 2020-07-13 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0011_checkoutorder_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutorder',
            name='id',
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='orderid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
