# Generated by Django 3.0.7 on 2020-07-13 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0013_delete_checkoutorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
                ('address1', models.CharField(default='', max_length=500)),
                ('address2', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zip_code', models.CharField(default='', max_length=10)),
                ('total', models.CharField(default='', max_length=50)),
                ('products', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
