# Generated by Django 3.0.7 on 2020-07-14 04:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0014_checkoutorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
